# Jekyll 配置文件

# 排除不需要构建的目录和文件
exclude:
  - node_modules/
  - "*/node_modules/"
  - "**/node_modules/"
  - vue/
  - bootstrap/
  - domo/
  - html/
  - package.json
  - package-lock.json
  - "*.json"
  - "*.md"
  - ".gitignore"
  - ".vscode/"
  - ".idea/"
  - "*.log"
  - "*.tmp"
  - "*.temp"
  - ".cache/"
  - "dist/"
  - "build/"

# 只包含需要的文件
include:
  - index.html
  - food.html
  - music.html
  - reading.html
  - "*.css"
  - "*.js"
  - "*.png"
  - "*.jpg"
  - "*.gif"

# 基本站点配置
title: "Git Learn 项目展示"
description: "个人学习项目展示网站"
baseurl: ""
url: "https://hbinlris.github.io"

# 插件
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag

# Markdown 处理器
markdown: kramdown
highlighter: rouge

# 其他设置
safe: true
incremental: false
